### ISSUE TITLE
정말 감사합니다! 문의 있어서 올려봅니다!

### ISSUE THREAD

**Issue by Junteacher** [obtuse-triangle/neisScheduleToICS#2]
정말감사합니다. 학사일정을 아주 쉽게 넣을 수 있습니다ㅠㅠ 정말 필요했는데 정말감사드립니다.
궁금한 점은 나이스에서 학사일정이 변경되면 다시 ics 파일을 다운받아서 캘린더에 등록해야 되나요?

**Comment by obtuse-triangle** [comment]
다운로드 받은 후 적용하는 것이 아닌, 다음 사진과 같이 캘린더 앱에서 구독 캘린더 추가를 통해서 링크를 추가하면 변경사항이 자동으로 업데이트 됩니다.

![image](https://github.com/obtuse-triangle/neisScheduleToICS/assets/61399718/52f1f517-44bb-44fc-a204-779c8f2cdfc0)
